<a href="https://colab.research.google.com/github/SamanaDahal1/AI-and-ML/blob/main/Worksheet0_SamanaDahal_2409014.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Task- 1:
# Create a Python program that converts between different units of measurement.
# • The program should:
# 1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
# 2. Ask the user to input the value to be converted.
# 3. Perform the conversion and display the result.
# 4. Handle potential errors, such as invalid input or unsupported conversion types.
# • Requirements:
# 1. Functions: Define at least one function to perform the conversion.
# 2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
# 3. User Input: Prompt the user to select the conversion type and input the value.
# 4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
# return value.
# • Conversion Options:
# 1. Length:– Convert meters (m) to feet (ft).– Convert feet (ft) to meters (m).
# 2. Weight:– Convert kilograms (kg) to pounds (lbs).– Convert pounds (lbs) to kilograms (kg).
# 3. Volume:– Convert liters (L) to gallons (gal).– Convert gallons (gal) to liters (L)
def convert(unit,value):
  if unit=="m":
    return value*3.28084
  elif unit=="ft":
    return value/3.28084
  elif unit=="kg":
    return value*2.20462
  elif unit=="lbs":
    return value/2.20462
  elif unit=="l":
    return value*0.2641
  elif unit=="gal":
    return value/0.2641
  else:
    return "Invalid unit"

try:
  unit=input("Enter the unit to be coverted (m for meter),(ft for feet),(kg for kilogram),(lbs for pound), (l for length),(gal for gallons):  ").lower()
  value=float(input("Enter the value that you want to covert: "))
  print(convert(unit,value))
except ValueError:
    print("Invalid input")




Enter the unit to be coverted (m for meter),(ft for feet),(kg for kilogram),(lbs for pound), (l for length),(gal for gallons):  KG
Enter the value that you want to covert: 2
4.40924


In [ ]:
# Create a Python program that performs various mathematical operations on a list of numbers.
# • The Program should:
# 1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
# of the numbers).
# 2. Ask the user to input a list of numbers (separated by spaces).
# 3. Perform the selected operation and display the result.
# 4. Handle potential errors, such as invalid input or empty lists.
# • Requirements:
# 1. Functions: Define at least one function for each operation (sum, average, maximum, mini
# mum).
# 2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
# empty lists).
# 3. User Input: Prompt the user to select the operation and input the list of numbers.
# 4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
# return value.
def add(num):
    """Return sum of numbers in the list."""
    return sum(num)

def avg(num):
    """Return average of numbers in the list."""
    return sum(num) / len(num)

def maximum(num):
    """Return maximum of numbers in the list."""
    return max(num)

def minimum(num):
    """Return minimum of numbers in the list."""
    return min(num)

print("Choose Operation: (1: sum), (2: average), (3: maximum), (4: minimum)")

try:
    choice = int(input("Enter your choice (1-4): "))
    num = list(map(float, input("Enter the numbers separated by spaces: ").split()))

    if not num:
        print("List is empty!")
    elif choice == 1:
        print("Sum =", add(num))
    elif choice == 2:
        print("Average =", avg(num))
    elif choice == 3:
        print("Maximum =", maximum(num))
    elif choice == 4:
        print("Minimum =", minimum(num))
    else:
        print("Invalid choice!")

except ValueError:
    print("Invalid input! Please enter numbers only.")
except ZeroDivisionError:
    print("Cannot calculate of empty list.")

Choose Operation: (1: sum), (2: average), (3: maximum), (4: minimum)
Enter your choice (1-4): 3
Enter the numbers separated by spaces: 7 5
Maximum = 7.0


In [ ]:
# Extract Every Other Element:
# Write a Python function that extracts every other element from a list, starting from the first element.
# • Requirements:– Define a function extract
# every
# other(lst) that takes a list lst as input and returns a
# new list containing every other element from the original list.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5]

def extract(lst):
    """
    every element from a list starting with the first element
    Args:
        lst: Input list
    Returns:
        List with alternate elements
    """
    return lst[::2]

list1=[1,2,3,4,5,6]
result=extract(list1)
print(f"Og list: {list1}")
print(f"other element: {result}")

list2= ['a','b','c','d','e']
result2=extract(list2)
print("Og list:",list2)
print("Every other element:",result2)

Og list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]
Original list: ['a', 'b', 'c', 'd', 'e']
Every other element: ['a', 'c', 'e']


In [ ]:
# Write a Python function that returns a sublist from a given list, starting from a specified index and
# ending at another specified index.
# • Requirements:– Define a function get
# sublist(lst, start, end) that takes a list lst, a starting index
# start, and an ending index end as input and returns the sublist from start to end (inclusive).– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
# be [3, 4, 5]

def sublist(lst, start, end):
    """Return sublist from start index to end index"""
    return lst[start:end+1]

num=[1,2,3,4,5,6]
result = sublist(num,2,4)

print("Og list:", num)
print("Sublist:", result)


Og list: [1, 2, 3, 4, 5, 6]
Sublist: [3, 4, 5]


In [ ]:
# Reverse a List Using Slicing:
# Write a Python function that reverses a list using slicing.
# • Requirements:– Define a function reverse
# slicing.
# list(lst) that takes a list lst and returns a reversed list using– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].
def rev(lst):
    """Return the reversed list using slicing"""
    return lst[::-1]

num=[1,2,3,4,5]
result=rev(num)

print("OG list:", num)
print("Reversed list:", result)

OG list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


In [ ]:
#  Remove the First and Last Elements:
# Write a Python function that removes the first and last elements of a list and returns the resulting
# sublist.
# • Requirements:– Defineafunction remove
# first
# last(lst) that takes a list lst and returns a sublist without
# the first and last elements using slicing.– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].
def remove(lst):
    """Return list without the first and last elements."""
    return lst[1:-1]

num= [1,2,3,4,5]
result = remove(num)

print("Og list:", num)
print("Result:", result)

Og list: [1, 2, 3, 4, 5]
Result: [2, 3, 4]


In [ ]:
#  Get the First n Elements:
# Write a Python function that extracts the first n elements from a list.
# • Requirements:– Define a function get
# first
# n(lst, n) that takes a list lst and an integer n as input and
# returns the first n elements of the list using slicing.– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].
def get(lst, n):
    """Return the first n elements of the list."""
    return lst[:n]

num=[1,2,3,4,5]
result = get(num,3)

print("Og list:",num)
print("First 3 elements:",result)

Og list: [1, 2, 3, 4, 5]
First 3 elements: [1, 2, 3]


In [ ]:
#  Extract Elements from the End:
# Write a Python function that extracts the last n elements of a list using slicing.
# • Requirements:– Define a function get
# last
# n(lst, n) that takes a list lst and an integer n as input and
# returns the last n elements of the list.– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].
def get(lst, n):
    """Return the last n elements of the list."""
    return lst[-n:]

num=[1,2,3,4,5]
result=get(num, 2)

print("Og list:",num)
print("Last 2 elements:",result)

Og list: [1, 2, 3, 4, 5]
Last 2 elements: [4, 5]


In [ ]:
#  Extract Elements in Reverse Order:
# Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
# element and skipping one element in between.
# • Requirements:– Define a function reverse
# skip(lst) that takes a list lst and returns a new list containing
# every second element starting from the second-to-last, moving backward.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].
def get(lst):
    """Return every second element in reverse starting from second to last."""
    return lst[-2::-2]

num=[1,2,3,4,5,6]
result=get(num)

print("Og list:",num)
print("Reverse skip result:", result)

Og list: [1, 2, 3, 4, 5, 6]
Reverse skip result: [5, 3, 1]


In [ ]:
def flatten(lst):
    """Flatten a nested list into a single list."""
    return [item for sublist in lst for item in sublist]

nest=[[1,2],[3,4],[5]]
result=flatten(nest)

print("Og list:", nest)
print("Flattened list:", result)

Og list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


In [ ]:
#  Accessing Nested List Elements:
# Write a Python function that extracts a specific element from a nested list given its indices.
# • Requirements:– Define a function access
# nested
# element(lst, indices) that takes a nested list lst and
# a list of indices indices, and returns the element at that position.– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
# 2], the output should be 6.
def access(lst, indices):
    """Return the element from a nested list using a list of indices."""
    element = lst
    for idx in indices:
        element = element[idx]
    return element

nest = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [2,1]
result = access(nest, indices)

print("Nested list:", nest)
print("Indices:", indices)
print("Accessed element:", result)


Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Indices: [2, 1]
Accessed element: 8


In [ ]:
# Sum of All Elements in a Nested List:
# Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
# • Requirements:– Define a function sum
# nested(lst) that takes a nested list lst and returns the sum of all
# the elements.– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.
def summ(lst):
    """Return the sum of all numbers in a nested list of any depth."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += summ(item)
        else:
            total += item
    return total

nest= [[1, 2], [3, [4, 5]], 6]
result = summ(nest)

print("Nested list:", nest)
print("Sum of all elements:", result)


Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


In [ ]:
#  Remove Specific Element from a Nested List:
# Write a Python function that removes all occurrences of a specific element from a nested list.
# • Requirements:– Define a function remove
# element(lst, elem) that removes elem from lst and returns the
# modified list.– Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,theoutputshould
# be [[1], [3], [4, 5]]
def remove(lst, elem):
    """Remove all occurrences of elem from a nested list."""
    return [[x for x in sublist if x != elem] for sublist in lst]

nest= [[1, 2], [3, 2], [4, 5]]
element_rem=2
result=remove(nest,element_rem)

print("Original list:", nest)
print("List after removing:", result)

Original list: [[1, 2], [3, 2], [4, 5]]
List after removing: [[1], [3], [4, 5]]


In [ ]:
#  Find the Maximum Element in a Nested List:
# Write a Python function that finds the maximum element in a nested list (regardless of depth).
# • Requirements:– Define a function find
# element.
# max(lst) that takes a nested list lst and returns the maximum– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.
def find(lst):
    """Return the maximum element in a nested list of any depth."""
    maximum = float('-inf')
    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find(item))
        else:
            maximum = max(maximum, item)
    return maximum


nest=[[1, 2], [3, [4, 5]], 6]
result = find(nest)

print("Nested list:", nest)
print("Maximum element:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6


In [ ]:
# Count Occurrences of an Element in a Nested List:
# Write a Python function that counts how many times a specific element appears in a nested list.
# • Requirements:– Define a function count
# occurrences(lst, elem) that counts the occurrences of elem in
# the nested list lst.– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould
# be 3.
def count_occ(lst, elem):
    """Count how many times elem appears in a nested list."""
    count=0
    for item in lst:
        if isinstance(item, list):
            count += count_occ(item, elem)
        elif item == elem:
            count += 1
    return count

nest=[[1, 2], [2, 3], [2, 4]]
element_count=2
result=count_occ(nest, element_count)

print("Nested list:", nest)
print(f"Occurrences of {element_count}:", result)

Nested list: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


In [ ]:
# Flatten a List of Lists of Lists:
# Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
# • Requirements:– Define a function deep
# flatten(lst) that takes a deeply nested list lst and returns a single
# f
# lattened list.– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
# [1, 2, 3, 4, 5, 6, 7, 8].
def deep(lst):
    """Return a flattened list from a deeply nested list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep(item))
        else:
            result.append(item)
    return result

nest=[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result=deep(nest)

print("Original list:", nest)
print("Flattened list:", result)

Original list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# Nested List Average:
# Write a Python function that calculates the average of all elements in a nested list.
# • Requirements:– Define a function average
# of all the elements.
# nested(lst) that takes a nested list lst and returns the average– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.
def average(lst):
    """Return the average of all elements in a nested list."""
    total = 0
    count = 0
    for sub in lst:
        for item in sub:
            total += item
            count += 1
    return total / count

num = [[1, 2], [3, 4], [5, 6]]
result = average(num)

print("Og list:", num)
print("Average:", result)

Og list: [[1, 2], [3, 4], [5, 6]]
Average: 3.5


In [ ]:
#numpy
import numpy as np

# 1. Initialize an empty array with size 2x2
arr1 = np.empty((2,2))
print("Empty array:\n", arr1)

# 2. Initialize an all ones array with size 4x2
arr2 = np.ones((4,2))
print("Ones array:\n", arr2)

# 3. Create array filled with a specific value
arr3 = np.full((3,3), 7)
print("Full array:\n", arr3)

# 4. Zeros array with same shape and type as arr2
arr4 = np.zeros_like(arr2)
print("Zeros like array:\n", arr4)

# 5. Ones array with same shape and type as arr2
arr5 = np.ones_like(arr2)
print("Ones like array:\n", arr5)

# 6. Convert list to numpy array
newList = [1,2,3,4]
arr6 = np.array(newList)
print("List to array:", arr6)

Empty array:
 [[4.05526860e-315 0.00000000e+000]
 [4.08295263e-315 4.07726834e-315]]
Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros like array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Ones like array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
List to array: [1 2 3 4]


In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two arrays
print("Addition:\n", x + y)

# 2. Subtract the two arrays
print("Subtraction:\n", x - y)

# 3. Multiply array with an integer
print("Multiply x by 2:\n", x * 2)

# 4. Square of each element
print("Square of x:\n", x**2)

# 5. Dot product
print("Dot product v·w:", np.dot(v, w))
print("Dot product x·v:\n", np.dot(x, v))
print("Dot product x·y:\n", np.dot(x, y))

# 6. Concatenate
print("Concatenate x and y along rows:\n", np.concatenate((x,y), axis=0))
print("Concatenate v and w along column:\n", np.vstack((v,w)))

# 7. Concatenate x and v
print("Try concatenate x and v:")
# because x is 2D and v is 1D
# treating v as a row to stack on x
print(np.vstack((x,v)))

Addition:
 [[ 6  8]
 [10 13]]
Subtraction:
 [[-4 -4]
 [-4 -3]]
Multiply x by 2:
 [[ 2  4]
 [ 6 10]]
Square of x:
 [[ 1  4]
 [ 9 25]]
Dot product v·w: 219
Dot product x·v:
 [29 77]
Dot product x·y:
 [[19 22]
 [50 58]]
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [[ 9 10]
 [11 12]]
Try concatenate x and v:
[[ 1  2]
 [ 3  5]
 [ 9 10]]


In [1]:
import time
import numpy as np
lst1= list(range(1000000))
lst2= list(range(1000000))
arr1=np.array(lst1)
arr2=np.array(lst2)
a=time.time()
c=lst1+lst2
b=time.time()
print("time taken by normal list calculation", b-a)
d=time.time()
f=arr1+arr2
e=time.time()
print("time taken by numpy", e-d)


time taken by normal list calculation 0.024730205535888672
time taken by numpy 0.011102914810180664


In [2]:
import time
import numpy as np
lst1= list(range(1000000))
lst2= list(range(1000000))
arr1=np.array(lst1)
arr2=np.array(lst2)
start=time.time()
c=[a * b for a, b in zip(lst1, lst2)]
end=time.time()
print("time taken by normal list calculation", end-start)
d=time.time()
f=arr1*arr2
e=time.time()
print("time taken by numpy", e-d)

time taken by normal list calculation 0.18443560600280762
time taken by numpy 0.003614187240600586


In [3]:

import time
import numpy as np
lst1= list(range(1000000))
lst2= list(range(1000000))
arr1=np.array(lst1)
arr2=np.array(lst2)
start=time.time()
c = sum(a * b for a, b in zip(lst1, lst2))
end=time.time()
print("time taken by normal list calculation", end-start)
d=time.time()
f=np.dot(arr1,arr2)
e=time.time()
print("time taken by numpy", e-d)

time taken by normal list calculation 0.2096250057220459
time taken by numpy 0.00222015380859375


In [4]:
import time

n = 1000

# Create two 1000x1000 matrices using lists
A = [[i for i in range(n)] for _ in range(n)]
B = [[j for j in range(n)] for _ in range(n)]

# Matrix multiplication with lists
start = time.time()
result_list = [[sum(A[i][k] * B[k][j] for k in range(n)) for j in range(n)] for i in range(n)]
end = time.time()

print("Time taken with Python lists:", end - start, "seconds")

Time taken with Python lists: 197.5952570438385 seconds
